service: job-hustler # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  searchClearbit:
    handler: api/handler.searchClearbit
    events:
      - http: 
          path: /search
          method: GET
          cors: true
          authorizer: aws_iam

  getUser:
    handler: api/handler.getUser
    events:
      - http:
          path: /user
          method: GET
          cors: true
          authorizer: aws_iam

  enrollUser:
    handler: api/handler.enrollUser
    events:
      - http:
          path: /enroll
          method: GET
          cors: true
          authorizer: aws_iam

  


