service: job-hustler # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  searchClearbit:
    handler: src/handler.searchClearbit
    events:
      - http: 
          path: /search
          method: GET
          cors: true

  getUser:
    handler: src/handler.getUser
    events:
      - http:
          path: /user
          method: GET
          cors: true

  enrollUser:
    handler: src/handler.enrollUser
    events:
      - http:
          path: /enroll
          method: GET
          cors: true

  


