service: job-hustler # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  searchClearbit:
    handler: api/handler.searchClearbit
    events:
      - http:
          path: /search
          method: GET
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Access-Control-Allow-Origin
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          authorizer:
            arn: ${ssm:/jobhustler/cognito-arn~true} # ~true decrypts 

  getUser:
    handler: api/handler.getUser
    events:
      - http:
          path: /user
          method: GET
          cors: true
          authorizer:
            arn: ${ssm:/jobhustler/cognito-arn~true}

  enrollUser:
    handler: api/handler.enrollUser
    events:
      - http:
          path: /enroll
          method: GET
          cors: true
          authorizer:
            arn: ${ssm:/jobhustler/cognito-arn~true}

