service: job-hustler # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http: 
          path: /hello
          method: GET
          cors: true
